FROM redis:latest
#FROM redislabs/redistimeseries:latest
#COPY init.sh /usr/local/bin/redis-init.sh
#RUN chmod +x /usr/local/bin/redis-init.sh
#ENTRYPOINT ["sh", "-c", "redis-server --loadmodule /usr/lib/redis/modules/redistimeseries.so & /usr/local/bin/redis-init.sh"]
#CMD ["/usr/local/bin/redis-init.sh"]
#CMD ["sh", "-c", "redis-server /usr/local/etc/redis/redis.conf & sleep 5 && /usr/local/bin/redis-init.sh"]

