run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - revive
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell

linters-settings:
  revive:
    rules:
      - name: var-naming
        arguments:
          - error
      - name: exported
        arguments:
          - error
      - name: package-comments
        arguments:
          - error
      - name: exported
        arguments:
          - error
      - name: var-naming
        arguments:
          - error
        disabled-rules:
          - package-comments

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosimple
        - staticcheck
        - unused

  max-issues-per-linter: 0
  max-same-issues: 0 