version: "2"

run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - revive
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
  settings:
    revive:
      rules:
        - name: var-naming
          arguments:
            - error
        - name: exported
          arguments:
            - error
        - name: package-comments
          arguments:
            - error

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0 