apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      volumes:
        - name: server-js
          configMap:
            name: frontend-server-js
      containers:
        - name: frontend
          volumeMounts:
            - name: server-js
              mountPath: /app/server.js
              subPath: server.js
