apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  type: ExternalName
  externalName: ingress-nginx-controller.ingress-nginx.svc.cluster.local
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
