# Dockerfile.dev
FROM golang:1.24-alpine
RUN apk add --no-cache git bash
RUN go install github.com/air-verse/air@latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /usr/local/bin/jobctl ./cmd/jobctl
ENV IN_CONTAINER=true
ENV POLYGON_API_KEY="ogaqqkwU1pCi_x5fl97pGAyWtdhVLJYm"
ENTRYPOINT ["air","-c",".air.toml"]
