# Dockerfile.dev
FROM golang:1.24-alpine
RUN apk update && \
    apk add --no-cache --retry 3 \
    git \
    bash \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    font-noto-emoji || \
    (apk update && apk add --no-cache \
    git \
    bash \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    font-noto-emoji) \
    && rm -rf /var/cache/apk/*

# Configure Chromium
ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/ \
    CHROMIUM_FLAGS="--disable-software-rasterizer --disable-dev-shm-usage"

RUN go install github.com/air-verse/air@latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /usr/local/bin/jobctl ./cmd/jobctl
ENV IN_CONTAINER=true
ENTRYPOINT ["air","-c",".air.toml"]
