// Code generated by tools/defgen/gen.go; DO NOT EDIT.

package strategies

// --- Base Definitions ---
// These slices are directly populated from defs.yaml
var (
	securityFeatures    = []string{"ticker", "sector", "industry", "market", "locale", "primaryExchange", "active"}
	ohlcvFeatures       = []string{"open", "high", "low", "close", "volume"}
	fundamentalFeatures = []string{"marketCap", "sharesOutstanding", "eps", "revenue", "dividend", "socialSentiment", "fearGreed", "shortInterest", "borrowFee"}
	timeframes          = []string{"1", "1h", "1d", "1w"}
	outputTypes         = []string{"raw", "rankn", "rankp"}
	comparisonOperators = []string{"<", "<=", ">", ">="}
	exprOperators       = []string{"+", "-", "*", "/", "^"}
	directions          = []string{"asc", "desc"}
)

// --- Derived Sets for Validation ---
// These maps (sets) are created for efficient 'contains' checks.
var (
	validSecurityFeatures    = toSet(securityFeatures)
	validOhlcvFeatures       = toSet(ohlcvFeatures)
	validFundamentalFeatures = toSet(fundamentalFeatures)
	validTimeframes          = toSet(timeframes)
	validOutputTypes         = toSet(outputTypes)
	validComparisonOperators = toSet(comparisonOperators)
	validExprOperators       = toSet(exprOperators)
	validDirections          = toSet(directions)
)

// toSet converts a string slice into a map[string]struct{} (a set)
// for efficient membership checking.
func toSet(items []string) map[string]struct{} {
	set := make(map[string]struct{}, len(items))
	for _, item := range items {
		set[item] = struct{}{}
	}
	return set
}

