FROM timescale/timescaledb-ha:pg17
USER root
RUN apt-get update && apt-get install -y cron
ENV PGDATA /var/lib/postgresql/data
EXPOSE 5432
COPY init/ /docker-entrypoint-initdb.d/
COPY config/dev.conf /etc/postgresql/postgresql.conf
RUN mkdir -p /migrations
COPY migrations/*.sql /migrations/
COPY scripts/migrate.sh /app/migrate.sh
RUN chmod +x /app/migrate.sh
COPY scripts/migrate.sh /app/migrate.sh
RUN chmod +x /app/migrate.sh
COPY scripts/start.sh /app/start.sh
RUN chmod +x /app/start.sh
ENTRYPOINT ["/app/start.sh"]
